### ISSUE TITLE
Package on NPM does not include window.d.ts

### ISSUE THREAD

**Issue by cuibonobo** [fusepilot/cep-interface#6]
There is a reference to `window.d.ts` in the `cs-interface.d.ts` file, but the `window.d.ts` file is not included in the NPM package. In addition, the reference in `cs-interface.d.ts` points to `../src/window.d.ts` instead of `./window.d.ts`.

The missing reference is causing build errors for me.

**Comment by liwp** [comment]
This issue remains in the 0.5.1 release, presumably because the `files` section in `package.json` includes only `lib`: https://github.com/fusepilot/cep-interface/blob/master/package.json#L9-L11
